apiVersion: v1
kind: Service
metadata: 
  name: nginxApp-service
  namespace: mywork
spec:
  type: NodePort
  selector: 
    name: nginxApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
